version: "2.1"

networks:
  # docker network create aether_internal
  aether:
    external:
      name: aether_internal

services:
  rest-proxy:
    image: ehealthafrica/scheduled-rest-proxy
    build: .
    stdin_open: true
    tty: true
    environment:
     - LOG_LEVEL=DEBUG
     - PORT=${PORT}
     - USERNAME=${USERNAME}
     - PASSWORD=${PASSWORD}
     - REALM=${REALM}
    depends_on:
      redis:
        condition: service_started
    ports:
     - "${PORT}:${PORT}"
    volumes:
     - ./conf:/code/conf
    command: start
    networks:
      - aether

  redis:
    image: redis:3-alpine
    command: ["--notify-keyspace-events", "KA", "--appendonly", "yes"]
    networks:
      - aether
